/*
  Warnings:

  - The values [USER_REJECT] on the enum `ONLINEORDERSTATUS` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ONLINEORDERSTATUS_new" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'PROCESSING', 'DELIVERING', 'REJECT', 'USER_CANCEL');
ALTER TABLE "order" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "order" ALTER COLUMN "status" TYPE "ONLINEORDERSTATUS_new" USING ("status"::text::"ONLINEORDERSTATUS_new");
ALTER TYPE "ONLINEORDERSTATUS" RENAME TO "ONLINEORDERSTATUS_old";
ALTER TYPE "ONLINEORDERSTATUS_new" RENAME TO "ONLINEORDERSTATUS";
DROP TYPE "ONLINEORDERSTATUS_old";
ALTER TABLE "order" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;
